%===============================================================================
% File:         Butterworth.m
% Written by:   Generated via MATLAB DSP Toolbox (Configured by Harry Rogers)
% Date:         January 2026
% Description:  Discrete-time Butterworth IIR low-pass filter object definition
%===============================================================================

function Hd = Butterworth
%BUTTERWORTH Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.1 and DSP System Toolbox 25.1.
% Generated on: 09-Jan-2026 14:14:21

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 44100;  % Sampling Frequency

N  = 11;    % Order
Fc = 1800;  % Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc, Fs);
Hd = design(h, 'butter');

% [EOF]
